baseurl      = "http://joanigq.github.io/"
title        = "joan_codes"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir = "docs"

enableThemeToggle = false
PygmentsCodeFences = false
# PygmentsStyle = "atom-one-dark"

defaultContentLanguageInSubdir = false


[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Joan Gonzalez"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "01/02/2006"
  dateformNumTime = "01/02/2006 15:04"
  homeSubtitle = ""

[params.logo]
logoMark     = ">"
logoText     = "joan_codes"
logoHomeLink = "/"

[params.footer]
trademark = true
rss = true
copyright = true
author = true

    
bottomText = [
    "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    "Made with &#10084"
]


  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Joan Gonzalez"
    subtitle = "Personal Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
   [languages.es]
    title = "Joan Gonzalez"
    subtitle = "Blog Personal"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Leer otras publicaciones"

  # And you can even create generic menu
    [menu]
    [[menu.main]]
        identifier = "about"
        name       = "About"
        url        = "about/"
    [[menu.main]]
        identifier = "posts"
        name       = "Posts"
        url        = "posts/"


  [[params.social]]
    name = "email"
    url  = "mailto:jgquiroga@dc.uba.ar"

  [[params.social]]
    name = "github"
    url  = "https://github.com/joangq"

